data_path: 'dataset/processed/'
benchmark_filename: [train, valid, test]
alias_of_item_id: [item_id_list]
load_col:
  inter: [user_id, item_id_list, item_id]
train_neg_sample_args: ~

topk: [10, 50]
metrics: [Recall, NDCG]
valid_metric: NDCG@10
eval_batch_size: 2048
stopping_step: 10
